# Runs rule tests on PRs targeting the master.

name: Tests
on:
  pull_request:
    branches: master

jobs:
  build:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 20.x

      - name: Install dependencies
        run: yarn

      - name: Rule tests
        run: yarn test
